name: Build flutter app

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
            channel: stable
            flutter-version: 3.22.0

      - run: flutter --version
      - run: dart --version
      - run: flutter config --no-cli-animations
      - run: flutter pub get
      - run: flutter build apk


  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
            channel: stable
            flutter-version: 3.22.0

      - run: flutter --version
      - run: dart --version
      - run: flutter config --no-cli-animations
      - run: flutter pub get
      - run: flutter build ios --no-codesign
